### PR TITLE
port to Quilt

### PR DESCRIPTION
**Pull request by JieningYu**

### CODE REVIEW

**Comment by JieningYu** [comment]
no problems!

**Comment by Flamarine** [comment]
no quilt is toxic why quilt (even if fabric is fully compatible)
i dont really get the point of using quilt. is it just a symbolic meaning to represent your disapproval or even contempt for fabric? fabric is as modern as quilt, and i havent discovered any performance differences yet. isnt this isolating fabric?

**Comment by Flamarine** [comment]
also im not saying that quilt is bad or evil. quilt did make some exciting changes, but that should not be the only reason why all the fabric mods and modpacks should move to quilt. this is unfair for fabric.

**Comment by JieningYu** [comment]
可以创建fabric分支，毕竟二者对于整合包差异较小。

**Comment by JieningYu** [comment]
此外，正版与离线玩家都可以正常的使用quilt。若无人使用quilt，那么它存在的意义就仅仅是为社区提供quilt mappings和quiltflower吗？此整合包内绝大部分mod都基于fabric开发（少部分使用了qsl），在fabric与quilt间转换并非难事，所以这绝不是在”孤立“fabric。可以发现，在移植quilt后开发的Cabricality utils也基于fabric开发，这同样是为二者间的转换提供便利。如果要对每一个有quilt移植的项目表示不解，那我同样也会对这种行为表示不解。

**Comment by Flamarine** [comment]
just confused about whether quilt is a good replacement of fabric. in my opinion, to improve an existing product is fine, but to replace the product is extremely a bad thing. not everyone in the community are happy with tons of ruptured mod loaders.
tysm for spending your time to answer my confusions.

**Pull request merged**
